### ISSUE TITLE
Build fails "No pkg-config found for opensc library"

### ISSUE THREAD

**Issue by tedd-wq** [carblue/acos5#3]
I cannot seem to build on Arch. Am I doing something wrong?

```
   Compiling opensc-sys v0.1.0 (https://github.com/carblue/opensc-sys?rev=7094a2d#7094a2d2)
   Compiling acos5_64 v0.0.15 (/home/tedd/build/acos5_64-0.0.15)
error: failed to run custom build command for `acos5_64 v0.0.15 (/home/tedd/build/acos5_64-0.0.15)`

Caused by:
  process didn't exit successfully: `/home/tedd/build/acos5_64-0.0.15/target/release/build/acos5_64-b49471eba3e0c860/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'No pkg-config found for opensc library', build.rs:46:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `opensc-sys v0.1.0 (https://github.com/carblue/opensc-sys?rev=7094a2d#7094a2d2)`

Caused by:
  process didn't exit successfully: `/home/tedd/build/acos5_64-0.0.15/target/release/build/opensc-sys-a5e1f2ee916a9754/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'No pkg-config found for opensc library', /home/tedd/.cargo/git/checkouts/opensc-sys-d9f8aea32b8a0fb4/7094a2d/build.rs:41:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by carblue** [comment]
Hi,
it looks like You forgot to install package pkg-config (as it is named on Ubuntu; maybe different name for other distros?). It's package description says:
"pkg-config is a system for managing library compile and link flags that works with automake and autoconf.
Increasingly libraries ship with ".pc" files that allow querying of the compiler and linker flags needed to use them through the pkg-config(1) program."

Does installing that solve the issue?

**Comment by carblue** [comment]
Please take that serious when README.md says:
"Look into build.rs first for some details about the libopensc binary (version etc.)."

**Comment by tedd-wq** [comment]
Thanks for replying.
I'm pretty sure I've got pkg-config. Arch has pkgconf (from https://github.com/pkgconf/pkgconf), which I think is compatible. I think the problem is that I don't have opensc.pc in /usr/lib/x86_64-linux-gnu. In fact, I don't even have that folder. I do have opensc installed, however.

I noticed that by building this package, it downloads opensc.pc to ./travis/opensc.pc and also to ~/.cargo/git/checkouts/opensc-sys-d9f8aea32b8a0fb4/7094a2d/travis/opensc.pc

I've never build a rust application before. I don't know what's going on.

**Comment by carblue** [comment]
I'll guide You through that issue.
0. There doesn't seem to be any issue relating to Rust. It's easy to use and You obviously installed and used it correctly and Your (error) output from cargo/rustc is what happens when processing the build.rs file fails.

We can skip the pkg-config "thing" and I'll tell You how to edit Your file build.rs tailored to Your system, if I get some more details. We will have to edit all build.rs files involved: of package opensc-sys, of acos5_64 and if You're using that, of acos5_64_pkcs15init as well. The part/section we are changing is and will afterwards be identical in all files build.rs. I will refer here to lines of build.rs in https://github.com/carblue/opensc-sys/blob/master/build.rs. Please make a backup copy so we are always referring to lines of that original (backup copy).

1. Run (from the opensc-sys directory) and tell about it's output:
cargo test test_struct_sizeof -- --nocapture

2. The version of OpenSC release installed: What is the output of invoking:
opensc-tool -i

3. In which directory are files beginning with libopensc.so* located, Please list those You have, including where potentially they point to.

**Comment by tedd-wq** [comment]
Thanks for assisting me with this.

1. Output of `cargo test test_struct_sizeof -- --nocapture`
```
   Compiling opensc-sys v0.1.0 (https://github.com/carblue/opensc-sys?rev=7094a2d#7094a2d2)
   Compiling acos5_64 v0.0.15 (/home/tedd/build/acos5_64-0.0.15)
error: failed to run custom build command for `opensc-sys v0.1.0 (https://github.com/carblue/opensc-sys?rev=7094a2d#7094a2d2)`

Caused by:
  process didn't exit successfully: `/home/tedd/build/acos5_64-0.0.15/target/debug/build/opensc-sys-783d8b6cf46d705d/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'No pkg-config found for opensc library', /home/tedd/.cargo/git/checkouts/opensc-sys-d9f8aea32b8a0fb4/7094a2d/build.rs:41:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `acos5_64 v0.0.15 (/home/tedd/build/acos5_64-0.0.15)`

Caused by:
  process didn't exit successfully: `/home/tedd/build/acos5_64-0.0.15/target/debug/build/acos5_64-cc2bef2c767d58d2/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib

--- stderr
thread 'main' panicked at 'No pkg-config found for opensc library', build.rs:47:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

2. Output of `opensc-tool -i`

```
OpenSC 0.19.0 [gcc  8.2.1 20181127]
Enabled features: locking zlib readline openssl pcsc(libpcsclite.so.1)
```

3. Output of `sudo find / -name "libopensc.so*"`
```
/usr/lib/libopensc.so.6.0.0
/usr/lib/libopensc.so
/usr/lib/libopensc.so.6
```

**Comment by carblue** [comment]
Okay.
Here is how to change https://github.com/carblue/opensc-sys/blob/master/build.rs
and likewise (other line nos 34-47 there) for acos5_64 (https://github.com/carblue/acos5_64/blob/master/build.rs) and acos5_64_pkcs15init

Delete lines 29-42 (including)
Insert at line 29:
```

    println!("cargo:rustc-link-search=native=/usr/lib"); // Posix,   the directory that contains libopensc.so
    println!("cargo:rustc-link-lib=opensc");
    println!("cargo:rustc-cfg=v0_19_0");
```

Thus Your opensc-sys/build.rs looks like
```

...
   4. If the following fails (used by cargo test), remove directory target, deactivate the following match pkg_config... {...} code block and activate the required lines println!("cargo:rustc-...=... manually in this build.rs.
*/
    println!("cargo:rustc-link-search=native=/usr/lib"); // Posix,   the directory that contains libopensc.so
    println!("cargo:rustc-link-lib=opensc");
    println!("cargo:rustc-cfg=v0_19_0");
/* in case of non-availability of pkg-config or failure of above, uncomment this block, comment-out the previous
...

```
Ref. 1: My fault. That can run successfully only after the before-mentioned changes were applied.  Please run that again and report. If that compiles and if it reports 
`test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 26 filtered out`
then the opensc-sys binding is okay and everything should build successfully now.

**Comment by carblue** [comment]
If we want to make it work with the original build.rs files - assuming Arch's  pkgconf (from https://github.com/pkgconf/pkgconf) is 100% compatible - then the failure reason probably was, as You stated already: You don't have opensc.pc and/or in a wrong place:
Once You know where .pc files are searched on Your system (i.e. where all the other .pc files are located; likely something like /usr/lib/pkgconfig), then create a file opensc.pc there, with content:
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include

Name: OpenSC smartcard framework
Description: OpenSC library
Version: 0.19.0
Libs: -L${libdir} -lopensc
```
PS: ./travis/opensc.pc is specific (and used only) for the travis CI testing (with Ubuntu Xenial installed there and an older OpenSC version, 0.17.0)

**Comment by tedd-wq** [comment]
I decided to go with your second suggestion and added the file /usr/lib/pkgconfig/opensc.pc with your suggested content. I then deleted all files in ~/.cargo and the acos5_64 build directory, and extracted a new set from your release archive. It was built without errors, but got the following output
```
   Compiling libc v0.2.62
   Compiling pkg-config v0.3.14
   Compiling opensc-sys v0.1.0 (https://github.com/carblue/opensc-sys?rev=7094a2d#7094a2d2)
   Compiling acos5_64 v0.0.15 (/home/tedd/build/acos5_64-0.0.15)
    Finished dev [unoptimized + debuginfo] target(s) in 8.91s
     Running target/debug/deps/acos5_64-ef2369bdcc4c608b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out
```
I copied `target/release/libacos5_64.so` to `/usr/lib` and edited `/etc/opensc.conf` so it shows the following
```
app default {
        # debug = 3;
        # debug_file = opensc-debug.txt;
        framework pkcs15 {
                # use_file_caching = true;
        }
        card_driver acos5_64 {
        # module, the (path/to/) filename of the driver library .so/.dll/.dylib. /path/to is dispensable if filename is in a 'standard library search path'
        module = /usr/lib/libacos5_64.so;

        # Disable / enable enquiry popup when performing a signature or RSA decrypt operation with ACOS5-64.
        # Operational only if compiled with cfg=enable_acos5_64_ui:
        # user_consent_enabled = yes; # anything starting with letter t or y (case-insensitive) get's interpreted as true/yes, otherwise false/no
        # When the dialog/popup window is shown: Answer with NO in order to decline the RSA key usage; YES or closing the window [X] means accepting RSA key usage
                }
        card_drivers = acos5_64, default; # for a painless start use  card_drivers = acos5_64, default;
        }
}
```
but the output of `opensc-tool -D` still doesn't show `acos5_64`.
Output:
```
Configured card drivers:
  cardos           Siemens CardOS
  flex             Schlumberger Multiflex/Cryptoflex
  cyberflex        Schlumberger Cyberflex
  gpk              Gemplus GPK
  gemsafeV1        Gemalto GemSafe V1 applet
  asepcos          Athena ASEPCOS
  starcos          STARCOS
  tcos             TCOS 3.0
  oberthur         Oberthur AuthentIC.v2/CosmopolIC.v4
  authentic        Oberthur AuthentIC v3.1
  iasecc           IAS-ECC
  belpic           Belpic cards
  incrypto34       Incard Incripto34
  acos5            ACS ACOS5 card
  akis             TUBITAK UEKAE AKIS
  entersafe        entersafe
  epass2003        epass2003
  rutoken          Rutoken driver
  rutoken_ecp      Rutoken ECP driver
  myeid            MyEID cards with PKCS#15 applet
  dnie             DNIe: Spanish eID card
  MaskTech         MaskTech Smart Card
  atrust-acos      A-Trust ACOS cards
  westcos          WESTCOS compatible cards
  muscle           MuscleApplet
  sc-hsm           SmartCard-HSM
  mcrd             MICARDO 2.1 / EstEID 1.0 - 3.5
  setcos           Setec cards
  PIV-II           Personal Identity Verification Card
  cac              Common Access Card (CAC)
  itacns           Italian CNS
  isoApplet        Javacard with IsoApplet
  gids             GIDS Smart Card
  openpgp          OpenPGP card
  jpki             JPKI(Japanese Individual Number Cards)
  coolkey          COOLKEY
  npa              German ID card (neuer Personalausweis, nPA)
  default          Default driver for unknown cards
```
Is there something else I have to do?

Edit: Gah, I'm an idiot. Put an extra closing curly brace in the config file.

Anyway, now the output of `opensc-tool -D`:
```
Configured card drivers:
  acos5_64         'acos5_64', suitable for ACOS5-64 v2.00 and v3.00 (Smart Card / CryptoMate64 / CryptoMate Nano)
  default          Default driver for unknown cards
```
But the output of `opensc-tool -n`:
```
Using reader with a card: Alcor Micro AU9560 00 00
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `-1212`,
 right: `0`', src/no_cdecl.rs:591:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```
And so, output of `RUST_BACKTRACE=1 opensc-tool -n`:
```
Using reader with a card: Alcor Micro AU9560 00 00
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `-1212`,
 right: `0`', src/no_cdecl.rs:591:13
stack backtrace:
   0: std::panicking::default_hook::{{closure}}
   1: std::panicking::default_hook
   2: std::panicking::rust_panic_with_hook
   3: std::panicking::continue_panic_fmt
   4: std::panicking::begin_panic_fmt
   5: acos5_64::no_cdecl::enum_dir
   6: acos5_64::no_cdecl::enum_dir
   7: acos5_64::acos5_64_init
   8: sc_connect_card
   9: <unknown>
  10: <unknown>
  11: __libc_start_main
  12: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

**Comment by carblue** [comment]
In opensc.conf, use
card_drivers = acos5_64, default;

and enable debug output:
debug = 3;
debug_file = /tmp/opensc-debug.log;

My opensc-debug.log starts with:
```
P:4193; T:0x139688627834752 08:40:15.099 [opensc-pkcs11] ctx.c:849:sc_context_create: ===================================
P:4193; T:0x139688627834752 08:40:15.099 [opensc-pkcs11] ctx.c:850:sc_context_create: opensc version: 0.20.0
P:4193; T:0x139688627834752 08:40:15.099 [opensc-pkcs11] reader-pcsc.c:857:pcsc_init: PC/SC options: connect_exclusive=0 disconnect_action=0 transaction_end_action=0 reconnect_action=0 enable_pinpad=1 enable_pace=1
P:4193; T:0x139688627834752 08:40:15.102 [opensc-pkcs11] ctx.c:498:load_dynamic_driver: successfully loaded card driver 'acos5_64'
```
If You don't get
`successfully loaded card driver 'acos5_64`
then Your opensc.conf file (probably in /etc/opensc/opensc.conf) has wrong entries.
Look at https://github.com/carblue/acos5_64

**Comment by tedd-wq** [comment]
Don't know if you noticed my edit to my last post. Just enabled debug output. The last few lines are:
```
0x7fd0c95ea740 23:22:40.297 [opensc-tool] card.c:465:sc_unlock: called
0x7fd0c95ea740 23:22:40.297 [opensc-tool] reader-pcsc.c:663:pcsc_unlock: called
0x7fd0c95ea740 23:22:40.303 [opensc-tool] iso7816.c:128:iso7816_check_sw: Authentication method blocked
0x7fd0c95ea740 23:22:40.303 [opensc-tool] sec.c:217:sc_pin_cmd: returning with: -1212 (Authentication method blocked)
```
I guess this means that the driver install went well? This is a card that I've already been playing around with, so I might have to pass a PIN.

**Comment by carblue** [comment]
Now i've read all of Your comment:
OpenSC and thus my driver is designed to work as much as possible without any PIN knowledge. So for many actions (all of opensc-tool) no pin is required. You'll know better than me which files on Your card/which actions are pin-protected, and only then OpenSC will start to ask for a PIN and remember that for max 10 uses (configurable) in a session.

- compiling/driver install is okay
- opensc.conf seems okay and You have debug output enabled. That's good in the beginning and required to locate issues, but when all runs smoothly, then set debug=0; to disable: The file is sensitive, it reveals pins and grows quickly, therefore I use debug_file = /tmp/opensc-debug.log;
to have it cleaned on a daily basis. Also, if You are using only ACOS5-64 V3.00, You may as well set
card_drivers = acos5_64, internal;
thereby enabling the use of all built-in drivers; (ACOS5-64 V**2**.00 with acos5_64 and internal ancient 'useless' driver acos5 can't coexist: they both claim to serve the same card).
- Thank You for trusting me/my code, but You don't need to copy libacos5_64.so to /usr/lib where it will run with root privileges. It's sufficient, more secure for You (if You don't trust me) and easier (with rebuilds) to let the entry 'module' point to libacos5_64.so's build location.

Sadly my testing pins slipped into the release build 0.0.15, thus You'll have to rebuild acos5_64 after manually fixing this:
In file acos5_64/src/no_cdecl.rs lines 590 and 591 place 2 consecutive slashes // at lines beginnings (thereby commenting-out the sc_verify call and the assert_eq (which caused the panic)).
The background for the pin verification there with my 'hardcoded testing pins' is this:
For ACOS5-64 V3.00 (You have that) there are several possible operation modes: FIPS (maybe the card detects itself to comply to FIPS card content requirements or not) or mode ACOS5-64 V2.00/64K or even others. If it's the first case (verified FIPS compliance), then reading of Security Environment Files in any case must be protected, and I wanted to simulate that there, but it's of course not okay to do that for the public with fixed/constant pins. Thus only if Your Security Environment Files are read-protected by a pin, then omit prepending // and instead enter Your Pins into lines 588 and 589. What is currently in there within [...], are the hexadecimal representations of 8 byte pins, "12345678" for the user pin and "87654321" for the SOPIN/admin pin. Replace that in the code according to Your actual pins (temporarily changing Your pins to those existing in the code will work only by other means like passing APDU commands to the card, e.g. with gscriptor from pcsctools and knowledge from the ref. manual). The next release will care for a general bugfix.

I'm a little bit confused, why Your card reports:
Using reader with a card: Alcor Micro AU9560 00 00

My  ACOS5-64 V3.00 (CryptoMate Nano) reports:
Using reader with a card: ACS CryptoMate (T2) 00 00

**Comment by tedd-wq** [comment]
Thanks again.
I commented out lines 590 and 591 like you suggested, (I think my first card got bricked by so many attempts, so I've been cautiously using a new one) and I'm using an initialised card but now all commands return "Security status not satisfied".

My ultimate goal is to use these cards as the security key for LUKS. I'm beginning to think maybe the OpenPGP card is better..

I'm using a smart card reader built into my Thinkpad, so that's why it reports as an Alcor reader.

**Comment by carblue** [comment]
For me with my card content crafted/tuned manually, the driver works well for my usage scenarios, mostly RSA, some AES/TDES crypto, but if You have a card that OpenSC supports well and for a longer time, than that may be a better fit (I don't know any other cards like the OpenPGP one).

The problem with implementing for driver 'acos5_64' is, that it proceeds slowly, because the OpenSC API documentation is horrible (sparse), the code base huge and complex, the ACOS5-64 reference manuals heavily flawed and they seem to tend to hide some essential details here and there, and the features of ACOS5-64 are difficult to implement and so on. Therefore I haven*t yet implemented card initialization, which may be the problem now.
I assume, You  initialized Your card with the ACS client kit software, which doesn't result in a (required for OpenSC usage)  PKCS#15 compliant state. Or did You  initialize in another way?

Yes I realized that about the reader. I'm used to using USB sticks only where reader/card is pretty much the same text, thus overlooked that.

I assume, LUKS relies on symmetric ciphers (only). If so, then IMO support is bad generally in OpenSC before coming version 0.20.0. E.g. no support for arbitrary IV for CBC in current 0.19.0, IIRC

**Comment by carblue** [comment]
LUKS, I don't know much about that, except what I just googled. My understanding: It's drive en-/de-cryption where the key(s) are on the drive already and en-/de-cryption is done in software (passing huge amounts of data through a smart card chip would be horribly slow, thus that would be wrong anyway). So the thing to be protected is the passphrase for LUKS?. That might be stored on the smart card, protected by card's pin and/or key authentication, or?. If You -same as I - don't know exactly how that has to work in a secure manner and what is required from a smart card, people at OpenSC may perhaps know: https://github.com/OpenSC/OpenSC/issues often get well-informed replies.
If You need secured Pin-entry (smartcard), then ACOS5-64 V2.00 is definitely the wrong choice: They go in plaintext from keyboard to smart card. With ACOS5-64 V3.00, secured pin-entry depends on Secure Messaging support and a special (directory) setup. It is said to work but I never succeeded to setup this (one of the undisclosed secrets in reference manual). ACS told me to get a client kit version 4.5 and reinitialize (the setup is part of the initialization as well when creating the directories) BUT that didn't work and I lost a CryptoMate Nano in immutable, useless for me state. Before losing my last one I stopped any further trials. My Secure Messaging support will come late, if ever. Another way of protection is by authenticating keys, but that requires key's duplicates to be present somewhere on the system (outside of the card) accessible to the driver, which is (on it's own) in no way more secure than placing the LUKS passphrase straightaway on Your system/USB stick or wherever. So, with my current ACOS5-64 support, that seems to fall off Your candidate list.

**Comment by tedd-wq** [comment]
I believe LUKS encrypts the data with a psuedo-randomly-generated key, which is in turn encrypted with the user password. This enables the user to change the key easily without having to re-encrypt all the data again with the new key. I also believe the key is stored in RAM so all data need not pass through the card to be de/recrypted. 

Nevertheless, it does seem that ACOS5 may not be in my future. I really appreciate the assistance.
